-- Originally seeded the Singapore example cards (UOB One / HSBC
-- Revolution / Citi Cash Back) and two example merchants unconditionally
-- on every deploy. WP5 (0018_config_review.sql) moved that data into
-- load_example_data_singapore() / clear_example_data() — invoked
-- explicitly from the dashboard's "Load the Singapore example" /
-- "Clear example data" actions, never automatically — so a fresh
-- deployment starts with an EMPTY card configuration (the chosen product
-- behaviour: first run is empty, not someone else's card list) rather
-- than inheriting this project's own worked example.
--
-- This file is intentionally left with nothing to run. It keeps its
-- migration number (0002) rather than being deleted or renumbered, so
-- migration history stays append-only and any environment that already
-- recorded 0002 as applied does not need special handling.
--
-- See 0018_config_review.sql's header for the full contract, and
-- docs/reference-example-sg.md's "Sources" section for the original T&C
-- citations behind the example numbers (unchanged, just relocated).
